name: Create Patch

on:
    issues:
        types: [opened]
    workflow_dispatch:
        inputs:
            startSha:
                required: true
            endSha:
                required: true

jobs:
    create-patch:
        runs-on: ubuntu-latest
        if: startsWith(github.event.issue.title, 'Patch:')
        steps:
            - uses: actions/checkout@v2
            - name: Checkout nopCommerce
              run: git clone https://github.com/nopSolutions/nopCommerce
            - name: Create directory
              run: mkdir ./patches/
            - name: Create Patch
              run: |
                  title="${{ github.event.issue.title }}"
                  shas=${title/Patch: /""}
                  echo "$shas"
                  IFS=_ read startSha endSha <<< $shas
                  git --git-dir ./nopCommerce/.git diff $startSha\^..$endSha --relative=src > ./patches/$startSha_$endSha.patch
                  zip ./patches/$startSha_$endSha.zip ./patches/$startSha_$endSha.patch
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config user.name "github-actions[bot]"
                  git add ./patches/$startSha_$endSha.zip
                  git commit -m "Add new patch"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
